require 'faraday'
require 'faraday_middleware'
require 'gorillib'
require 'gorillib/metaprogramming/class_attribute'
require 'gorillib/string/inflections'
require 'logger'
require 'multi_json'

require 'vayacondios/client/configuration'
require 'vayacondios/client/http_methods'
require 'vayacondios/client/http_client'
